### ISSUE TITLE
Plugin broken - Player has never played before on this server.

### ISSUE THREAD

**Issue by Rubbertjuh** [KaiKikuchi/DeletePlayerData#1]
Hello
I'm currently trying out this plugin. But it seems that this isn't working anymore.
I'm running CB 1.7.10 on kCauldron.
Running Tekkit Legends modpack.

It keeps saying that there is no player named that way, I've tried both UUID and Names. Case sensitive.

**Comment by KaiKikuchi** [comment]
Hello. We use this plugin on all our modpacks (TL included) and we're using kCauldron. It works fine.

If the message is "This player has never played before on this server.", that means Bukkit reports the player has never played on the server.

https://github.com/KaiKikuchi/DeletePlayerData/blob/master/src/main/java/net/kaikk/mc/dpd/CommandExec.java#L49

**Comment by Rubbertjuh** [comment]
That's strange.
Does it only work if the player has joined the server after the plugin was installed? 
Or does it check the playerdata folder?

If it checks the playerdata folder, do I enter a UUID or Player?
I've tried them both but it doesn't seem to work.

**Comment by KaiKikuchi** [comment]
1- Bukkit will automatically load the player.dat file and will tell you if the player has joined the server. It doesn't matter if the player has joined before the plugin was added... but if you delete his player.dat with this plugin (or manually), it'll show you that message because the data has been deleted.
2- You must enter a player name. UUIDs are not allowed.
3- It deletes the player.dat file. e.g. if I want to delete my player.dat file with the plugin, I type "/deleteplayerdata KaiNoMood" and the plugin will delete my player.dat file located at "world/playerdata/a54a7884-9ea4-4d54-ac35-1623d70ffbe1.dat"

**Comment by Rubbertjuh** [comment]
Alright I think I know what the issue is.
We're running the World/Plugins from a RAMDISK.
Due to it having another directory, this may be the issue why it's giving this error.

Would it be possible to add in a function where you can configure the path?
If it takes to much time to implement, don't bother! 

Thanks a lot for the help.

**Comment by KaiKikuchi** [comment]
Added in version 1.1
https://github.com/KaiKikuchi/DeletePlayerData/releases/tag/v.1.1

**Comment by Rubbertjuh** [comment]
wow! 
Thanks a lot!

You'll hear from me if this works.

**Comment by Rubbertjuh** [comment]
Update: Would you be able to give an example of how a path would look like?
Right now I need to remove it from the following path: /mnt/ramdisk/mcservers/gamemodes/toastcraft/world/playerdata

Do I put it in "" ? Or just put the full path in the config?

**Comment by KaiKikuchi** [comment]
Use double quotes if there's a space on the path. Otherwise it's the same.

**Comment by Rubbertjuh** [comment]
For some reason it doesn't seem to work. 
I guess I'm doing something wrong. Mind giving me an example?
Sorry for asking these stupid questions.

Current config: 
# playerdata folder path. It can be relative to the server folder.
PlayerDataPath: "/mnt/ramdisk/mcservers/gamemodes/toastcraft/world/playerdata"

**Comment by KaiKikuchi** [comment]
Can you post the server log?

**Comment by Rubbertjuh** [comment]
There is nothing to see in the server.log
It just says that the player can not be found.

**Comment by KaiKikuchi** [comment]
The player has to join the server first. After you make him joining the server, you can use that command on him.
